---
abstract: 'Ordered Moose sugar'
author:
  - 'Jan Henning Thorsen C<< jhthorsen at cpan.org >>'
build_requires:
  Class::MOP: 1
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-BatmanBeforeRobin
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 1
  namespace::autoclean: 0.09
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-BatmanBeforeRobin
  homepage: http://search.cpan.org/dist/MooseX-BatmanBeforeRobin
  repository: git://github.com/jhthorsen/moosex-batmanbeforerobin.git
version: 0.03
